captureDirectory: ./captures
completeDirectory: ./complete
modelScanInterval: 30
minFileSizeMb: 10
port: 9080
debug: false
models: []
includeModels: []
includeUids: []
excludeModels: []
excludeUids: []
deleteModels: []
deleteUids: []
