captureDirectory: /Users/sstativa/Sites/mfc-node/captures
completeDirectory: /Users/sstativa/Sites/mfc-node/complete
modelScanInterval: 30
debug: true
models:
  - uid: 3052158
  - uid: 17988279
  - uid: 7784644
    nm: Brielle
    excluded: true
includeModels: []
excludeModels: []
